Repository wp-cli/eval-command, pull requests merged in 2019-04, with the labels that each got.

#35 Handle #! in file inputs - idea #108
  features/eval.feature
  src/EvalFile_Command.php
Labels: command:eval-file

#36 Move PHP 5.4 tests from `WP_VERSION` `latest` to `5.1`
  .travis.yml
Labels: scope:distribution

#38 Fix handling of `__FILE__` and `__DIR__` constants in `eval()`'d code.
  features/eval.feature
  src/EvalFile_Command.php
Labels: bug, command:eval-file

#40 Enhancement: Add PHP 7.3 to Travis CI build matrix
  .travis.yml
Labels: scope:testing

#41 Implement CS checking based on the `WP_CLI_CS` ruleset
  .distignore
  .gitignore
  composer.json
  eval-command.php
  phpcs.xml.dist
  src/EvalFile_Command.php
Labels: scope:testing
